# Generated by Django 5.1.4 on 2024-12-06 10:45

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('image_1', models.ImageField(default='images/default-image.jpg', upload_to='aticle_images')),
                ('image_2', models.ImageField(default='images/default-image.jpg', upload_to='aticle_images')),
                ('image_3', models.ImageField(default='images/default-image.jpg', upload_to='aticle_images')),
                ('description_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_3', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('for_banner', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_category', to='category.category')),
                ('tags', models.ManyToManyField(related_name='articles_tags', to='category.tag')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
